// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220307215555_schema")]
    partial class schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "descripcion 1",
                            Name = "nombre 1",
                            Price = 206m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "descripcion 2",
                            Name = "nombre 2",
                            Price = 221m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "descripcion 3",
                            Name = "nombre 3",
                            Price = 181m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "descripcion 4",
                            Name = "nombre 4",
                            Price = 244m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "descripcion 5",
                            Name = "nombre 5",
                            Price = 16m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "descripcion 6",
                            Name = "nombre 6",
                            Price = 32m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "descripcion 7",
                            Name = "nombre 7",
                            Price = 139m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "descripcion 8",
                            Name = "nombre 8",
                            Price = 217m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "descripcion 9",
                            Name = "nombre 9",
                            Price = 61m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "descripcion 10",
                            Name = "nombre 10",
                            Price = 32m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "descripcion 11",
                            Name = "nombre 11",
                            Price = 43m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "descripcion 12",
                            Name = "nombre 12",
                            Price = 178m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "descripcion 13",
                            Name = "nombre 13",
                            Price = 16m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "descripcion 14",
                            Name = "nombre 14",
                            Price = 278m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "descripcion 15",
                            Name = "nombre 15",
                            Price = 207m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "descripcion 16",
                            Name = "nombre 16",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "descripcion 17",
                            Name = "nombre 17",
                            Price = 32m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "descripcion 18",
                            Name = "nombre 18",
                            Price = 214m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "descripcion 19",
                            Name = "nombre 19",
                            Price = 249m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "descripcion 20",
                            Name = "nombre 20",
                            Price = 4m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "descripcion 21",
                            Name = "nombre 21",
                            Price = 181m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "descripcion 22",
                            Name = "nombre 22",
                            Price = 34m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "descripcion 23",
                            Name = "nombre 23",
                            Price = 120m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "descripcion 24",
                            Name = "nombre 24",
                            Price = 38m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "descripcion 25",
                            Name = "nombre 25",
                            Price = 125m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "descripcion 26",
                            Name = "nombre 26",
                            Price = 75m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "descripcion 27",
                            Name = "nombre 27",
                            Price = 291m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "descripcion 28",
                            Name = "nombre 28",
                            Price = 280m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "descripcion 29",
                            Name = "nombre 29",
                            Price = 118m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "descripcion 30",
                            Name = "nombre 30",
                            Price = 187m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "descripcion 31",
                            Name = "nombre 31",
                            Price = 117m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "descripcion 32",
                            Name = "nombre 32",
                            Price = 32m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "descripcion 33",
                            Name = "nombre 33",
                            Price = 79m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "descripcion 34",
                            Name = "nombre 34",
                            Price = 107m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "descripcion 35",
                            Name = "nombre 35",
                            Price = 64m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "descripcion 36",
                            Name = "nombre 36",
                            Price = 129m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "descripcion 37",
                            Name = "nombre 37",
                            Price = 96m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "descripcion 38",
                            Name = "nombre 38",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "descripcion 39",
                            Name = "nombre 39",
                            Price = 128m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "descripcion 40",
                            Name = "nombre 40",
                            Price = 13m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "descripcion 41",
                            Name = "nombre 41",
                            Price = 52m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "descripcion 42",
                            Name = "nombre 42",
                            Price = 264m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "descripcion 43",
                            Name = "nombre 43",
                            Price = 289m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "descripcion 44",
                            Name = "nombre 44",
                            Price = 102m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "descripcion 45",
                            Name = "nombre 45",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "descripcion 46",
                            Name = "nombre 46",
                            Price = 211m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "descripcion 47",
                            Name = "nombre 47",
                            Price = 282m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "descripcion 48",
                            Name = "nombre 48",
                            Price = 14m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "descripcion 49",
                            Name = "nombre 49",
                            Price = 26m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "descripcion 50",
                            Name = "nombre 50",
                            Price = 19m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "descripcion 51",
                            Name = "nombre 51",
                            Price = 37m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "descripcion 52",
                            Name = "nombre 52",
                            Price = 156m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "descripcion 53",
                            Name = "nombre 53",
                            Price = 84m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "descripcion 54",
                            Name = "nombre 54",
                            Price = 136m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "descripcion 55",
                            Name = "nombre 55",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "descripcion 56",
                            Name = "nombre 56",
                            Price = 172m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "descripcion 57",
                            Name = "nombre 57",
                            Price = 102m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "descripcion 58",
                            Name = "nombre 58",
                            Price = 143m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "descripcion 59",
                            Name = "nombre 59",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "descripcion 60",
                            Name = "nombre 60",
                            Price = 241m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "descripcion 61",
                            Name = "nombre 61",
                            Price = 40m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "descripcion 62",
                            Name = "nombre 62",
                            Price = 158m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "descripcion 63",
                            Name = "nombre 63",
                            Price = 99m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "descripcion 64",
                            Name = "nombre 64",
                            Price = 174m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "descripcion 65",
                            Name = "nombre 65",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "descripcion 66",
                            Name = "nombre 66",
                            Price = 12m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "descripcion 67",
                            Name = "nombre 67",
                            Price = 99m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "descripcion 68",
                            Name = "nombre 68",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "descripcion 69",
                            Name = "nombre 69",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "descripcion 70",
                            Name = "nombre 70",
                            Price = 79m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "descripcion 71",
                            Name = "nombre 71",
                            Price = 24m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "descripcion 72",
                            Name = "nombre 72",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "descripcion 73",
                            Name = "nombre 73",
                            Price = 87m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "descripcion 74",
                            Name = "nombre 74",
                            Price = 236m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "descripcion 75",
                            Name = "nombre 75",
                            Price = 251m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "descripcion 76",
                            Name = "nombre 76",
                            Price = 217m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "descripcion 77",
                            Name = "nombre 77",
                            Price = 45m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "descripcion 78",
                            Name = "nombre 78",
                            Price = 19m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "descripcion 79",
                            Name = "nombre 79",
                            Price = 182m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "descripcion 80",
                            Name = "nombre 80",
                            Price = 214m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "descripcion 81",
                            Name = "nombre 81",
                            Price = 92m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "descripcion 82",
                            Name = "nombre 82",
                            Price = 278m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "descripcion 83",
                            Name = "nombre 83",
                            Price = 254m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "descripcion 84",
                            Name = "nombre 84",
                            Price = 99m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "descripcion 85",
                            Name = "nombre 85",
                            Price = 150m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "descripcion 86",
                            Name = "nombre 86",
                            Price = 260m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "descripcion 87",
                            Name = "nombre 87",
                            Price = 248m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "descripcion 88",
                            Name = "nombre 88",
                            Price = 243m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "descripcion 89",
                            Name = "nombre 89",
                            Price = 174m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "descripcion 90",
                            Name = "nombre 90",
                            Price = 191m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "descripcion 91",
                            Name = "nombre 91",
                            Price = 27m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "descripcion 92",
                            Name = "nombre 92",
                            Price = 252m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "descripcion 93",
                            Name = "nombre 93",
                            Price = 153m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "descripcion 94",
                            Name = "nombre 94",
                            Price = 187m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "descripcion 95",
                            Name = "nombre 95",
                            Price = 273m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "descripcion 96",
                            Name = "nombre 96",
                            Price = 194m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "descripcion 97",
                            Name = "nombre 97",
                            Price = 165m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "descripcion 98",
                            Name = "nombre 98",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "descripcion 99",
                            Name = "nombre 99",
                            Price = 186m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "descripcion 100",
                            Name = "nombre 100",
                            Price = 144m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 264
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 211
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 301
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 104
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 156
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 155
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 432
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 356
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 185
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 158
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 116
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 195
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 119
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 396
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 294
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 456
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 415
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 280
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 160
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 467
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 462
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 138
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 460
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 223
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 455
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 186
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 488
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 341
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 145
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 150
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 293
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 211
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 274
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 266
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 196
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 449
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 467
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 407
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 167
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 407
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 307
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 135
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 157
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 241
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 323
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 495
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 187
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 470
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 370
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 396
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 461
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 472
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 128
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 160
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 376
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 326
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 370
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 222
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 420
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 204
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 279
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 294
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 210
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 371
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 231
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 293
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 150
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 357
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 278
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 180
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 206
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 488
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 409
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 184
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 297
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 338
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 102
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 165
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 314
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 313
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
